name: disease_prediction
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  body_part_selector: ^0.0.3
  flutter_svg: ^1.1.6
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  fluttertoast: ^8.2.1
  firebase_database: ^10.0.16
  flutter_secure_storage: ^7.0.1
  radio_grouped_buttons: ^1.0.1
  http: 0.13.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  flutter_native_splash: ^2.2.19

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
